import type { NextPage } from 'next';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import axios from 'axios';

import { IPost } from '../interfaces';
import { Post, HomeSidebar } from '../components';

const Home: NextPage = ({}) => {
  const [posts, setPosts] = useState<IPost[]>([]);
  const [observedPost, setObservedPost] = useState('');
  const [currentPage, setCurrentPage] = useState(1);

  useEffect(() => {
    if (!posts || !posts.length) return;
    const id = posts.at(-1)?.identifier;

    if (id !== observedPost && id) {
      setObservedPost(id);
      observeElement(document.getElementById(id)!);
    }
  }, [posts]);

  const observeElement = (element: HTMLElement) => {
    if (!element) return;
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          console.log('reached bottom');
          setCurrentPage(currentPage + 1);
          observer.unobserve(element);
        }
      },
      { threshold: 1 }
    );
    observer.observe(element);
  };

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        const { data } = await axios.get('/posts/?page=' + currentPage);
        setPosts([...posts, ...data]);
      } catch (error) {
        console.log(error);
      }
    };
    fetchPosts();
  }, [currentPage]);

  return (
    <div className="px-4">
      <Head>
        <title>Reddit: the frontpage of the internet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div className="container flex pt-4">
        <div className="w-full md:w-[40rem]">
          {posts.map((post) => {
            return (
              <Post setPosts={setPosts} key={post.identifier} post={post} />
            );
          })}
        </div>
        <HomeSidebar />
      </div>
    </div>
  );
};;

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   try {
//     const { data } = await axios.get('/posts');
//     console.log(data);
//     return {
//       props: {
//         posts: data,
//       },
//     };
//   } catch (error) {
//     return {
//       props: { error: 'Something went wrong' },
//     };
//   }
// };

export default Home;
