import type { NextPage } from 'next';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import axios from 'axios';

import { IPost } from '../interfaces';
import { Post, HomeSidebar } from '../components';

const Home: NextPage = ({}) => {
  const [posts, setPosts] = useState<IPost[]>([]);

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        const { data } = await axios.get('/posts');
        setPosts(data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchPosts();
  }, []);

  return (
    <div className="px-4">
      <Head>
        <title>Reddit: the frontpage of the internet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div className="container flex pt-4">
        <div className="w-full sm:w-[40rem]">
          {posts.map((post) => {
            return <Post key={post.identifier} post={post} />;
          })}
        </div>
        <HomeSidebar />
      </div>
    </div>
  );
};

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   try {
//     const { data } = await axios.get('/posts');
//     console.log(data);
//     return {
//       props: {
//         posts: data,
//       },
//     };
//   } catch (error) {
//     return {
//       props: { error: 'Something went wrong' },
//     };
//   }
// };

export default Home;
