import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';

import { IPost } from '../interfaces';
import { Post } from '../components';

interface HomePageProps {
  posts: IPost[];
}

const Home: NextPage<HomePageProps> = ({ posts }) => {
  return (
    <div className="px-4 pt-12">
      <Head>
        <title>Reddit: the frontpage of the internet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div className="w-full lg:w-[976px] mx-auto flex pt-4">
        <div className="w-full sm:w-[40rem]">
          {posts.map((post) => {
            return <Post key={post.identifier} post={post} />;
          })}
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const { data } = await axios.get('/posts');

    return {
      props: {
        posts: data,
      },
    };
  } catch (error) {
    return {
      props: { error: 'Something went wrong' },
    };
  }
};

export default Home;
